task: 'video-anayltics'
dataset:
  video: ''
  music: ''
nodes:
  - id: 1 
    name: video-source
    knobs: 
  - id: 2
    name: detect-vehicles
    knobs:
      - name: model
        type: Category  
        value: 
          - 'yolov8n'
          - 'yolov8s'
          - 'yolov8m'
          - 'yolov8l'
          - 'yolov8x' 
edges:
  - source: 1
    to: 2